sudo: required
dist: trusty
language:
  - java
jdk:
  - oraclejdk8  # Building Bazel requires JDK8.
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg'
      - sourceline: 'ppa:marutter/rrutter'
    packages:
      - bazel
      - r-recommended
      - pylint

script:
  - ./lint.sh
  - bazel run @yarn//:yarn
  - bazel coverage --instrumentation_filter=//... //test/go/... //test/js/... //test/jvm/... //test/clang/...
  - ./test/test_golden.sh
  - bazel build //report:bin
  - bazel-bin/report/bin --dest_dir=$(pwd)/gh-pages

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages
  local-dir: gh-pages
